import{a as R,S,i as n}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))f(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&f(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function f(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const q="51361824-00dcf0a42679c337e9a38d381",E="https://pixabay.com/api/",P=15;async function h(r,o=1){return(await R.get(E,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P}})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),c=document.querySelector("#load-more"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",o),B.refresh()}function $(){p.innerHTML=""}function g(){m.classList.add("visible")}function b(){m.classList.remove("visible")}function M(){c.classList.remove("hidden"),c.disabled=!1}function u(){c.classList.add("hidden")}const L=document.querySelector("#search-form"),O=L.querySelector('input[name="searchQuery"]'),A=document.querySelector("#load-more");let d="",i=1,w=0,a=0;L.addEventListener("submit",async r=>{r.preventDefault();const o=O.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=o,i=1,a=0,$(),u(),g();try{const e=await h(d,i);w=e.totalHits,e.hits.length?(y(e.hits),a+=e.hits.length,v()):n.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch{n.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{b()}});A.addEventListener("click",async()=>{i+=1,u(),g();try{const r=await h(d,i);y(r.hits),a+=r.hits.length,I(),v()}catch{n.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{b()}});function v(){a>=w?(u(),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):M()}function I(){const r=document.querySelector(".gallery"),{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
