import{a as q,S as R,i as a}from"./assets/vendor-DqB7j7Ix.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const E="51361824-00dcf0a42679c337e9a38d381",P="https://pixabay.com/api/",M=15;async function g(o,r=1){return(await q.get(P,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:M}})).data}const y=document.querySelector(".gallery"),p=document.querySelector(".loader"),d=document.querySelector("#load-more"),$=new R(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){const r=o.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");y.insertAdjacentHTML("beforeend",r),$.refresh()}function A(){y.innerHTML=""}function L(){p.classList.add("visible")}function v(){p.classList.remove("visible")}function w(){d.classList.remove("hidden"),d.disabled=!1}function u(){d.classList.add("hidden")}const S=document.querySelector("#search-form"),B=S.querySelector('input[name="searchQuery"]'),h=document.querySelector("#loading-message"),I=document.querySelector("#load-more");let f="",l=1,m=0,n=0;S.addEventListener("submit",async o=>{o.preventDefault();const r=B.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}f=r,l=1,n=0,A(),u(),L(),h.classList.add("visible");try{const e=await g(f,l);m=e.totalHits,e.hits.length?(b(e.hits),n+=e.hits.length,n<m&&w()):a.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch{a.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{v(),h.classList.remove("visible")}});I.addEventListener("click",async()=>{l+=1,u(),L();try{const o=await g(f,l);b(o.hits),n+=o.hits.length,O(o.hits.length),n>=m?(u(),a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch{a.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{v()}});function O(o){const e=document.querySelector(".gallery").querySelectorAll(".gallery-item");if(e.length>0&&o>0){const i=e[e.length-o];i&&i.scrollIntoView({behavior:"smooth",block:"start"})}}
//# sourceMappingURL=index.js.map
