import{a as S,S as q,i as a}from"./assets/vendor-DqB7j7Ix.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))f(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&f(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function f(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const R="51361824-00dcf0a42679c337e9a38d381",E="https://pixabay.com/api/",P=15;async function p(r,s=1){return(await S.get(E,{params:{key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:P}})).data}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),c=document.querySelector("#load-more"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const s=r.map(t=>`
    <li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t.likes}</p>
        <p><b>Views:</b> ${t.views}</p>
        <p><b>Comments:</b> ${t.comments}</p>
        <p><b>Downloads:</b> ${t.downloads}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",s),B.refresh()}function M(){h.innerHTML=""}function b(){y.classList.add("visible")}function L(){y.classList.remove("visible")}function $(){c.classList.remove("hidden"),c.disabled=!1}function v(){c.classList.add("hidden")}const w=document.querySelector("#search-form"),O=w.querySelector('input[name="searchQuery"]'),m=document.querySelector("#loading-message"),l=document.querySelector("#load-more");let d="",i=1,u=0;w.addEventListener("submit",async r=>{r.preventDefault();const s=O.value.trim();if(!s){a.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=s,i=1,M(),v(),b(),m.classList.add("visible");try{const t=await p(d,i);u=t.totalHits,t.hits.length?(g(t.hits),i*15<u&&$()):a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch{a.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{L(),m.classList.remove("visible")}});l.addEventListener("click",async()=>{i+=1,b(),l.disabled=!0;try{const r=await p(d,i);g(r.hits),A(),i*15>=u?(v(),a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):l.disabled=!1}catch{a.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{L()}});function A(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
